name: Build QMK firmware

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: qmk/qmk_firmware
      qmk_ref: master
      preparation_command: |
        # Upgrade QMK CLI and toolchains
        apt-get -qq update
        DEBIAN_FRONTEND=noninteractive apt-get -qq install curl
        curl -LSfs https://install.qmk.fm/ | bash -s -- --confirm
        printf "%s/.local/bin\n" "$HOME" >>"$GITHUB_PATH"
        printf "%s/.local/share/qmk/bin\n" "$HOME" >>"$GITHUB_PATH"

  publish:
    name: 'QMK Userspace Publish'
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@main
    if: always() && !cancelled()
    needs: build
